Ecommerce/Ecommerceproject/Ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('shopapp',include('shopapp.urls')),
    path('search/',include('search_app.urls')),
    path('cartapp/',include('cartapp.urls')),
    # path('shop/', include('shopapp.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

Ecommerce/Ecommerceproject/cartapp/urls.py
from django.urls import path
from . import views
app_name = 'cartapp'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cartapp_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

Ecommerce/Ecommerceproject/search_app/urls.py
from django.urls import path
from . import views
app_name = 'search_app'

urlpatterns = [
    path('',views.SearchResult,name='SearchResult')
]

Ecommerce/Ecommerceproject/shopapp/urls.py
from django.urls import path
from . import views
app_name = 'shopapp'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail'),
]

Ecommerce/Ecommerceproject/cartapp/models.py
from django.db import models
from shopapp.models import Product

# Create your models here.

class Cart(models.Model) :
    cart_id = models.CharField(max_length = 250, blank = True)
    date_added = models.DateField(auto_now_add = True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model) :
    product = models.ForeignKey(Product,on_delete = models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete = models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default = True)

    class Meta:
        db_table = 'CartItem'

    def Sub_total(self) :
        return self.product.price * self.quantity
    
    def __str__(self) :
        return '{}'.format(self.product)
    
    

Ecommerce/Ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

Ecommerce/Ecommerceproject/shopapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 250, unique = True)
    slug = models.SlugField(max_length = 250, unique = True)
    description = models.TextField(blank = True)
    image = models.ImageField(upload_to='category',blank = True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
         return reverse('shopapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)
        
class Product(models.Model):
    name = models.CharField(max_length = 250, unique = True)
    slug = models.SlugField(max_length = 250, unique = True)
    description = models.TextField(blank = True)
    price = models.DecimalField(max_digits = 10, decimal_places = 2)
    Category = models.ForeignKey(Category,on_delete = models.CASCADE)
    image = models.ImageField(upload_to='Product',blank = True)
    stock = models.IntegerField()
    available = models.BooleanField(default = True)
    created = models.DateField(auto_now_add = True)
    updated = models.DateField(auto_now = True)

    def get_url (self):
        return reverse('shopapp:prodCatdetail', args=[self.Category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)
        

Ecommerce/Ecommerceproject/cartapp/views.py
from django.shortcuts import get_object_or_404, redirect, render
from shopapp.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()

    return cart

def add_cart(request,product_id):
    product = Product.objects.get(id = product_id)

    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))

    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id = _cart_id(request))
        cart.save(),

    try:
        cart_item = CartItem.objects.get(product = product, cart = cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()

    except CartItem.DoesNotExist :
        cart_item = CartItem.objects.create(product = product, quantity = 1, cart = cart)
        cart_item.save()

    return redirect('cartapp:cartapp_detail')

def cart_detail(request, total = 0, counter = 0, cart_items = None):
    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))
        cart_items = CartItem.objects.filter(cart = cart, active = True)

        for cart_item in cart_items :
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist :
        pass

    return render(request,'cart.html',dict(cart_items = cart_items, total = total, counter = counter))

def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Product,id = product_id)
    cart_item = CartItem.objects.get(product = product, cart = cart)
    if cart_item.quantity > 1 :
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartapp:cartapp_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Product,id = product_id)
    cart_item = CartItem.objects.get(product = product, cart = cart)
    cart_item.delete()
    return redirect('cartapp:cartapp_detail')

Ecommerce/Ecommerceproject/search_app/views.py
from django.shortcuts import render
from shopapp . models import Product
from django.db.models import Q

# Create your views here.

def SearchResult (request):
    products = None
    query = None
    if 'q' in request.GET :
        query = request.GET.get('q')
        if query.isalnum():
            products = Product.objects.all().filter(Q(name__contains = query) | Q(description__contains = query))
    return render(request, 'search.html',{'query':query, 'products':products})

    

Ecommerce/Ecommerceproject/shopapp/views.py
from django.shortcuts import get_object_or_404, render
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.
def allProdCat(request,c_slug = None):
    c_page = None
    products_list = None
    if c_slug != None :
        c_page = get_object_or_404(Category,slug = c_slug)
        products_list = Product.objects.all().filter(Category = c_page, available = True)
    else:
        products_list = Product.objects.all().filter(available = True)
    paginator = Paginator(products_list,6)

    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except(EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request,"category.html",{'category':c_page, 'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(Category__slug = c_slug, slug = product_slug)
    except Exception as e :
        raise e
    return render(request,'product.html',{'product':product})

Ecommerce/Ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">

    <script src="https://kit.fontawesome.com/90387e06ce.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body class="d-flex flex-column min-vh-100">
    <div class="container">
            {% include 'header.html' %}
            {% include 'navbar.html' %}
            {% block content %}
            {% endblock %}
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'js/slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</body>
</html>

Ecommerce/Ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    This is the cart page. Proceed to review your items & place the order.
    
{% endblock %}


{% block title %}
Cart-SHOPGLEAM Company PVT LTD.
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart Is Empty
        </h1>
        <br>
        <!-- <p class="text-center">Please Click
            <a href="{% url 'shopapp:allProdCat' %}">Here</a>To Continue Shopping.
        </p> -->
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
{% endif %}
<div class="row mx_auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{{ cart_item.product.get_url }}">
                            <img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image" height="100px;" width="100px;">
                        </a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU : {{cart_item.product.id}}
                        <br>
                        Price : $ {{cart_item.product.price}}
                        <br>
                        Qty : {{cart_item.quantity}} x {{cart_item}}
                    </td>
                    <td>
                        $ {{cart_item.Sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a">
                            <i class="fa-solid fa-plus custom_icon"></i>
                        </a>
                        &nbsp;
                        <a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a">
                            <i class="fa-solid fa-minus"></i>
                        </a>
                        &nbsp;
                        <a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_icon">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a">
                            <i class="fa-solid fa-minus"></i>
                        </a>
                        &nbsp;<a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_icon">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
            <tr>
                <th>
                    Check Out 
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Please review your shopping cart items before proceeding with the order payment
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your Total is : <strong>{{ total }}</strong>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="mx-auto">
        <a href="{% url 'shopapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
    </div>

</div>

</div>
{% endblock %}

Ecommerce/Ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}



{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        Welcome to SHOPGLEAM store, here you can buy unique collections.
    {% endif %}
{% endblock %}



{% block title %}
    {% if category %}
        {{category.name}} - SHOPGLEAM store
    {% else %}
        See Our New Collections - SHOPGLEAM store
    {% endif %}
{% endblock %}



{% block content %}
    {% if category %}
    <div>
        <div>
            <p style="text-align: center;">
                <a href="{% url 'shopapp:allProdCat' %}">Our Product Collections</a>
            </p>
        </div>
    </div>
    {% endif %}


    <div>
    {% if category %}
        <div style="text-align: center;">
            <img src="{{category.image.url}}" alt="{{category.name}}" style="width: 130px; height: 130px;">
        </div>
    </div>
        <br>
    <div>
        <h1>{{category.name}}</h1>
        <p>{{category.description}}</p>
    </div>
    {% else %}
    <div>
        <img src="{% static 'img/banner.png' %}" alt="Our Products" width="1150px;" max-width="100%;">
    </div>
        <br>
    <div>
        <h1>Our Product Collections</h1>
        <p>Welcome to ShopGleam, where fashion meets radiance! 🌟 Immerse yourself in a world of curated elegance and captivating style. At ShopGleam, we believe in transforming your shopping experience into a luminous journey, offering a carefully selected collection that sparkles with sophistication and glamour.</p>
    </div>
    {% endif %}

<div class="container">
    <div class="row mx_auto">
        {% for i in products.object_list %}
            <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                <div class="card text-center" style="min-width: 18rem;">
                    <a href="{{i.get_url}}"> 
                        {% if i.image %}
                        <img class="card-img-top my-image" src="{{i.image.url}}" alt="{{i.name}}" widht="50%;" height="350px;">
                        {% endif %}
                    </a>

                <div class="card-body">
                    <h4>{{i.name}}</h4>
                <p>{{i.price}}</p>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div><br>
</div>
{% endblock %}

Ecommerce/Ecommerceproject/templates/footer.html
<footer class="mt-auto">

<div class="footer navbar-fixed-bottom my-footer">
    <p class="text-center">
        &copy;SHOPGLEAM pvt ltd. All Rights Reserved
    </p>
</div>

</footer>

Ecommerce/Ecommerceproject/templates/header.html
{% load static %}
<header style="text-align: center;">
    <centre>
        <a href="{% url 'shopapp:allProdCat' %}"><img src="{% static 'img/logo_01.png' %}" alt="logimage" width="180px" height="180px;"></a>
    </centre>
</header>

Ecommerce/Ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="width: 1150px; margin: 0 auto;">
   
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
       
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shopapp:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'Shopapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Shop
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">

            <a class="dropdown-item" href="{% url 'shopapp:allProdCat' %}">All Products</a>
            {% for j in links %}
            <a class="dropdown-item" href="{{j.get_url}}">{{j.name}}</a>
            {% endfor %}
            
          </div>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cartapp:cartapp_detail' %}"><i class="fa-solid fa-cart-shopping"></i>{{item_count}}</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </nav>

Ecommerce/Ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.description|truncatewords:155}}
{% endblock %}


{% block title %}
    {% if category %}
        {{product.name}} - SHOPGLEAM
    {% endif %}
{% endblock %}

{% block content %}
<div class="container">
<div class="row my_prod_row_class">
    
    <div class="mx_auto">
        <p><a href="{% url 'shopapp:allProdCat' %}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
    <div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width : 18rem;">
            <img src="{{product.image.url}}" alt="{{product.name}}" height=130px; width=130px;>
        </div>
    </div>


<div class="col-12 col-sm-12 col-md-12 col-lg-6">
    <div>
        <h1 class="my_prod_title">{{product.name}}</h1>
        <p>${{product.price}}</p>
        <p class="my_title">Product Description</p>
        <p class="text-justify my_prod_text">${{product.description}}</p>
    {% if product.stock <= 0 %}
        <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
    {% else %}
        <a class="btn btn-secondary" href="{% url 'cartapp:add_cart' product.id %}">Add To Cart</a>
    {% endif %}
    </div>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

Ecommerce/Ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    Check out our products in SHOPGLEAM store.
    
{% endblock %}


{% block title %}
Search
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:<b>{{query}}</b></p>
</div>



<div class="container">
    <div class="row mx_auto">
        {% for i in products %}
            <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
                <div class="card text-center" style="min-width: 18rem;">
                    <a href="{{i.get_url}}"> 
                        {% if i.image %}
                        <img class="card-img-top my-image" src="{{i.image.url}}" alt="{{i.name}}" widht="50%;" height="350px;">
                        {% endif %}
                    </a>

                <div class="card-body">
                    <h4>{{i.name}}</h4>
                <p>{{i.price}}</p>
                </div>
                </div>
            </div>
          





{% empty %}
<div class="row mx_auto">
    <p class="text-center my_search_text">0 Results Found</p>
</div>
{% endfor %}
</div>
</div>
{% endblock %}